---
- name: Include Linux installation tasks
  include_tasks: install_linux.yml
  when: ansible_facts['os_family'] in ['Debian', 'RedHat']

- name: Include macOS installation tasks
  include_tasks: install_macos.yml
  when: ansible_facts['os_family'] == 'Darwin'

- name: Include verification tasks
  include_tasks: verify.yml
