---
- name: Check Feishin binary exists (Linux)
  stat:
    path: "{{ feishin_bin_path }}"
  register: feishin_bin_stat
  when: ansible_facts['os_family'] != 'Darwin'

- name: Check Feishin app bundle exists (macOS)
  stat:
    path: "{{ feishin_macos_app_path }}"
  register: feishin_bin_stat
  when: ansible_facts['os_family'] == 'Darwin'

- name: Assert Feishin is installed
  assert:
    that:
    - feishin_bin_stat.stat.exists | default(false) | bool
    fail_msg: "Feishin binary was not installed successfully"
